<section>
  <header class='page-header'>
    <h3> Todos as Categorias de Quarto </h3>
    <div class='text-right'><?= link_to('/admin/categorias-de-quarto/novo', 'Nova categoria') ?></div>
  </header>

  <article>
   <table class='table table-bordered table-striped'>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Data do Cadastro</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
       <?php foreach($room_categories as $room_category) {?>
          <tr>
            <td><?= $room_category->getName() ?></td>
            <td><?= format_date($room_category->getCreatedAt()); ?></td>
            <td class='options'>
              <ul>
                <li> <?= link_to("/admin/categorias-de-quarto/{$room_category->getId()}/editar", 'Editar')?></li>
                <li> <?= link_to("/admin/categorias-de-quarto/{$room_category->getId()}/deletar", 'Remover', "data-confirm='Tem certeza?'")?></li>
              </ul>
            </td>
          </tr>
       <?php } ?>
      </tbody>
    </table>
  </article>
</section>

