<!DOCTYPE>
<html lang="en">
<head>
      <meta charset="utf-8" />
      <title>Hotel Campeão - Campeão em qualidade atendimento e preço</title>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta name="description" content="" />
      <meta name="author" content="" />
    
      <!-- LOAD CSS FILES -->
      <?php stylesheet_include_tag('/css/main.css'); ?>   

      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>
<body>
   <!-- header begin -->
   <header>
      <div id="logo">
         <div class="inner">
            <a href="index.html"><img src="/hotel/app/assets/img/newlogo.png" alt="" /></a>
         </div>
      </div>
          
      <!-- mainmenu begin -->
      <div id="mainmenu-container">           
         <ul id="mainmenu">
            <li><?= link_to('/', 'Página Inicial') ?></li>
            <li><?= link_to('#', 'Quartos') ?>
               <ul>
                  <li><?= link_to('#', 'Lista de Quartos') ?></li>
                  <li><?= link_to('#', 'Detalhes de Quartos') ?></li>
               </ul>
            </li>
            <li><?= link_to('#', 'Reservas') ?></li>
            <li><?= link_to('#', 'Notícias') ?>
               <ul>
                  <li><?= link_to('#', 'Lista de Notícias') ?></li>
                 <li><?= link_to('#', 'Notícia Única') ?></li>
               </ul>
            </li>
            <li><?= link_to('#', 'Sobre a Empresa') ?></li>
            <li><?= link_to('#', 'Galeria') ?></li>
            <li><?= link_to('/fale-conosco', 'Fale Conosco') ?></li>
         </ul>
      </div>

   </header>
   <!-- header close -->

   <?php require $view; ?>

   <!-- footer begin -->
   <footer>
      <div class="container">
         <div class="row">
            <div class="span3">
               <img src="/hotel/app/assets/img/logo-2.png" alt="" />
            </div> 
            <div class="span3">
               <h3>About Us</h3>
                 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
            </div>                                
            <div class="span3">
               <h3>Latest News</h3>
               <ul class="list-news"> 
                  <li>
                     <img src="/hotel/app/assets/img/thumbnail-1.jpg" alt="" />
                     <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor</div>
                  </li>
                  <li>
                     <img src="/hotel/app/assets/img/thumbnail-1.jpg" alt="" />
                     <div class="text">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor</div>
                  </li>
               </ul>                
            </div>
            <div class="span3">
               <h3>Our Address</h3>
               <address> 80 Gotham Street, Sydney
                  <span><strong>Phone:</strong>(208) 222 4546</span>
                  <span><strong>Fax:</strong>(208) 222 4647</span>
                  <span><strong>Email:</strong><a href="mailto:contact@example.com">contact@example.com</a></span>
                  <span><strong>Web:</strong><a href="#test">http://example.com</a></span>
               </address>
                 
               <div class="social-icons">
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/rss.png" alt="" /></a>
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/facebook.png" alt="" /></a>
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/twitter.png" alt="" /></a>
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/gplus.png" alt="" /></a>
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/youtube.png" alt="" /></a>
                  <a href="#"><img src="/hotel/app/assets/img/social-icons/vimeo.png" alt="" /></a>
               </div>
            </div>
         </div>
      </div>
        
      <div class="subfooter">
         <div class="container">
            <div class="row">
               <div class="span6">&copy; Copyiright 2013 - Sunshine by Aveothemes</div>
               <div class="span6">
                  <nav><ul>
                     <li><a href="#">Home</a></li>
                     <li><a href="#">Room</a></li>
                     <li><a href="#">Booking</a></li>
                     <li><a href="#">News</a></li>
                     <li><a href="#">Gallery</a></li>
                     <li><a href="#">Contact</a></li>
                  </ul></nav>
               </div>
            </div>
         </div>
      </div>
        
   </footer>
   <!-- footer close -->

   <!-- LOAD JS FILES -->
   <?php javascript_include_tag('jquery.min.js','bootstrap.min.js', 'jquery.isotope.min.js', 'jquery.prettyPhoto.js', 'easing.js', 'jquery.lazyload.js', 'jquery.ui.totop.js', 'selectnav.js', 'ender.js', 'custom.js', 'responsiveslides.min.js', 'datepickr.js', 'application.js'); ?>
</body>
</html>