<section>
  <header class="page-header">
      <h1>Área administrativa</h1>
  </header>
  <article class='well'>
     <p>
      Seja bem-vindo á area administrativa!
     </p>
    <hr />
    <h3>Atividades que devem ser desenvolvidas</h3>
    <ul>
      <li>Cadastro, edição e remoção de usuário na área administrativa</li>
      <li>Visualização de uma mensagem na área administrativa</li>
      <li>Permitir que uma mensagem seja marcada como lida e não lida</li>
    </ul>
  </article>
</section>
